# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snake.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snake.proto',
  package='PnD',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bsnake.proto\x12\x03PnD\"6\n\x08Vector2D\x12\x0e\n\x01x\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y\"q\n\x05Snake\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1b\n\x04\x62ody\x18\x02 \x03(\x0b\x32\r.PnD.Vector2D\x12%\n\tdirection\x18\x03 \x01(\x0b\x32\r.PnD.Vector2DH\x01\x88\x01\x01\x42\x05\n\x03_idB\x0c\n\n_direction\"U\n\tGameState\x12!\n\x05\x66ruit\x18\x01 \x01(\x0b\x32\r.PnD.Vector2DH\x00\x88\x01\x01\x12\x1b\n\x07players\x18\x02 \x03(\x0b\x32\n.PnD.SnakeB\x08\n\x06_fruitb\x06proto3'
)




_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='PnD.Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PnD.Vector2D.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='PnD.Vector2D.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_x', full_name='PnD.Vector2D._x',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_y', full_name='PnD.Vector2D._y',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=20,
  serialized_end=74,
)


_SNAKE = _descriptor.Descriptor(
  name='Snake',
  full_name='PnD.Snake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PnD.Snake.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='PnD.Snake.body', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='PnD.Snake.direction', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='PnD.Snake._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_direction', full_name='PnD.Snake._direction',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=76,
  serialized_end=189,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='PnD.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fruit', full_name='PnD.GameState.fruit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='players', full_name='PnD.GameState.players', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_fruit', full_name='PnD.GameState._fruit',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=191,
  serialized_end=276,
)

_VECTOR2D.oneofs_by_name['_x'].fields.append(
  _VECTOR2D.fields_by_name['x'])
_VECTOR2D.fields_by_name['x'].containing_oneof = _VECTOR2D.oneofs_by_name['_x']
_VECTOR2D.oneofs_by_name['_y'].fields.append(
  _VECTOR2D.fields_by_name['y'])
_VECTOR2D.fields_by_name['y'].containing_oneof = _VECTOR2D.oneofs_by_name['_y']
_SNAKE.fields_by_name['body'].message_type = _VECTOR2D
_SNAKE.fields_by_name['direction'].message_type = _VECTOR2D
_SNAKE.oneofs_by_name['_id'].fields.append(
  _SNAKE.fields_by_name['id'])
_SNAKE.fields_by_name['id'].containing_oneof = _SNAKE.oneofs_by_name['_id']
_SNAKE.oneofs_by_name['_direction'].fields.append(
  _SNAKE.fields_by_name['direction'])
_SNAKE.fields_by_name['direction'].containing_oneof = _SNAKE.oneofs_by_name['_direction']
_GAMESTATE.fields_by_name['fruit'].message_type = _VECTOR2D
_GAMESTATE.fields_by_name['players'].message_type = _SNAKE
_GAMESTATE.oneofs_by_name['_fruit'].fields.append(
  _GAMESTATE.fields_by_name['fruit'])
_GAMESTATE.fields_by_name['fruit'].containing_oneof = _GAMESTATE.oneofs_by_name['_fruit']
DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['Snake'] = _SNAKE
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2D,
  '__module__' : 'snake_pb2'
  # @@protoc_insertion_point(class_scope:PnD.Vector2D)
  })
_sym_db.RegisterMessage(Vector2D)

Snake = _reflection.GeneratedProtocolMessageType('Snake', (_message.Message,), {
  'DESCRIPTOR' : _SNAKE,
  '__module__' : 'snake_pb2'
  # @@protoc_insertion_point(class_scope:PnD.Snake)
  })
_sym_db.RegisterMessage(Snake)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'snake_pb2'
  # @@protoc_insertion_point(class_scope:PnD.GameState)
  })
_sym_db.RegisterMessage(GameState)


# @@protoc_insertion_point(module_scope)
